export default {
    appLogo: require('./images/AppLogo.png'),
    back: require('./images/Back.png'),
    city: require('./images/city.png'),
    email: require('./images/Email.png'),
    google: require('./images/Google.png'),
    eye: require('./images/eye.png'),
    home: require('./images/home.png'),
    dummyProfile: require('./images/dummyProfile.png'),
    lock: require('./images/Lock.png'),
    mobile: require('./images/mobile.png'),
    setting: require('./images/setting.png'),
    profileicon: require('./images/profileicon.png'),
    welcomeBg: require('./images/welcomeBg.png'),
    apple: require('./images/apple.png'),
    meditation: require('./images/meditation.png'),
    layer: require('./images/layer.png'),
    userSqr: require('./images/userSqr.png'),
    fire: require('./images/fire.png'),
    morning: require('./images/morning.png'),
    apti: require('./images/apti.png'),
    time: require('./images/time.png'),
    send: require('./images/send.png'),
    repeate: require('./images/repeate.png'),
    play: require('./images/play.png'),
    backplay: require('./images/backplay.png'),
    next: require('./images/next.png'),
    crossPlay: require('./images/crossPlay.png'),
image2: require('./images/image2.png'),
image3: require('./images/image3.png'),
image4: require('./images/image4.png'),
image5: require('./images/image5.png'),

calm: require('./images/clam.png'),
focus: require('./images/focus.png'),
refelect: require('./images/refelect.png'),
playGreen: require('./images/playGreen.png'),

    lock2: require('./images/lock2.png'),
    check: require('./images/check.png'),
fruits: require('./images/bean2.png'),
  beans: require('./images/bean.png'),
  onion: require('./images/onion.png'),
  checkGreenIcon: require('./images/checkGreen.png'),
  crossRedIcon: require('./images/close.png'),
  chart: require('./images/chart.png'),
calendar: require('./images/calendar.png'),
food: require('./images/food.png'),
unlock: require('./images/Journal.png'),

english: require('./images/english.png'),
french: require('./images/french.png'),
arbi: require('./images/arbi.png'),
pp: require('./images/pp.png'),
support: require('./images/support.png'),
privacy: require('./images/privacy.png'),
notification: require('./images/notification.png'),
logout: require('./images/logout.png'),
help: require('./images/chat.png'),
language: require('./images/language.png'),

radio: require('./images/radio.png'),
radioUn: require('./images/radioun.png'),
  }; 